### ISSUE TITLE
谢谢廖老师的精彩课程,但是关于nodejs课程下的koa的model章节有一些问题,想要问一下

### ISSUE THREAD

**Issue by tent42** [michaelliao/learn-javascript#11]
首先是,当我跟着课程写db.js,不管是参照课程里的,还是参照github上的,都会报错:
sequelize deprecated String based operators are now deprecated. Please use Symbol based operators for better security,
我看有篇CSDN写了有关该课程是因为执行函数后面忘了写;分号.但是我几番检查,该处代码完全没有像([{+;之类的问题,而且问题出现在new sequellize里.除非是在new里声明operatorsAliases: false,否则一直warning.原因到底是因为什么?

其二是,在github上的代码,添加了课程里面没有的,当创建一个orm后会输出的console.log,这这里面有一些循环处理,但是 if (v instanceof dbType) 这句话一直报TypeError: Function has non-object prototype 'undefined' in instanceof check,应该是还要在嵌套一个if判断v的instanceof指向吧?

**Comment by michaelliao** [comment]
sequellize的版本问题，nodejs的库有个毛病，经常改api接口
