### ISSUE TITLE
无法clone 下来，下载zip，也下载不全就中断了

### ISSUE THREAD

**Issue by apple202078** [michaelliao/learn-javascript#19]

**Comment by michaelliao** [comment]
你的网络问题，找GitHub客服

**Comment by apple202078** [comment]
> 你的网络问题，找GitHub客服

嗯，我试了很多次，用git clone 试过，用axel 命令试过，直接浏览器下载试过，在家里试过，在办公室里试过。不过我已经看完你写的JavaScript文章了，非常不错，昨晚上用了三个小时都看完，代码我就不看了，因为我搞过Python，到时候哪里不明白，我会再看你写的网站。
