### ISSUE TITLE
关于templating.js

### ISSUE THREAD

**Issue by jinlarry** [michaelliao/learn-javascript#7]
你好廖老师
关于你的view-koa项目
不太明白为什么在templating.js中这样写

`function templating(path, opts) {
    var env = createEnv(path, opts);
    return async (ctx, next) => {
        ctx.render = function (view, model) {
            ctx.response.body = env.render(view, Object.assign({}, ctx.state || {}, model || {}));
            ctx.response.type = 'text/html';
        };
        await next();
    };
}`

请问这段代码是怎么使controller里面的ctx添加render()函数的？

**Comment by michaelliao** [comment]
有问题去网站提问
